[build]
  command = "npm install && npm run build"
  # the command to build your React app
  # you may need to adjust this depending on your app's setup

[deploy]
  command = "npm start"
  # the command to start your app
  # you may need to adjust this depending on your app's setup

[port]
  default = 3000
  # the port that your app listens on
  # you may need to adjust this depending on your app's setup